[ml]
client_id = "6624554871338107"
client_secret = "0YkXl4544wE7nUllAtTI6GOvtZ1mt6O1"
refresh_token = "TG-68a88ad95602ce0001c9fa4b-698492667"
site = "MLC" # Chile
# seller_id = "YOUR_SELLER_ID" # opcional; se obtiene automáticamente si no está


[app]
# límite de seguridad (requests/min) para evitar 429; ajustable
rpm_ceiling = 1400
bulk_size = 20 # ítems por /items?ids=...
bulk_workers = 64